version: "3.2"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=vj(3=4j&1hiu#rz08wjr@z(rzb$v*3$xfyyw*lw8&l*(54*25k
      - DEBUG=0
      - ENVIRONMENT=production
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
