# Generated by Django 2.2.7 on 2020-10-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0004_auto_20201008_1224'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='picture',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
